In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from lifelines import CoxPHFitter

In [2]:
df = pd.read_excel('Leaders.xlsx')
print(df.head())
print(df.isnull().sum())

   years  lost  manner  start  military   age  conflict    loginc  growth  \
0      3     2       1    975         0  53.0         1  5.799093    -5.7
1      8     0       0    979         0  37.0         1  5.799093    -5.7
2      3     3       0    960         0  44.0         1  4.700480     1.0
3      1     3       0    964         0  51.0         1  4.700480     1.0
4      1     3       1    965         1  56.0         1  4.700480     1.0

   pop    land  literacy  region
0  8.0  1247.0        20       1
1  8.0  1247.0        20       1
2  4.0   112.0        11       1
3  4.0   112.0        11       1
4  4.0   112.0        11       1
years        0
lost         0
manner       0
start        0
military     0
age         34
conflict     0
loginc       0
growth       0
pop          0
land         0
literacy     0
region       0
dtype: int64

In [3]:
df = df.dropna()

variables = ['manner', 'start', 'military', 'age', 'conflict',
            'loginc', 'growth', 'pop', 'land', 'literacy']



# Model 1: lost(0) — zdarzenie = 1, 2 lub 3
# m1 = fit_competing_cox(leaders, [1, 2, 3], 'Model 1: lost(0) — wszystkie zdarzenia')

# # Model 2: lost(0,1,2) — zdarzenie = 3 (non-constitutional)
# m2 = fit_competing_cox(leaders, [3], 'Model 2: lost(0,1,2) — zdarzenie: non-constitutional (type 3)')

# # Model 3: lost(0,1,3) — zdarzenie = 2 (nationalized)
# m3 = fit_competing_cox(leaders, [2], 'Model 3: lost(0,1,3) — zdarzenie: nationalized (type 2)')

# # Model 4: lost(0,2,3) — zdarzenie = 1 (consolidated)
# m4 = fit_competing_cox(leaders, [1], 'Model 4: lost(0,2,3) — zdarzenie: consolidated (type 1)')

In [4]:
cph = CoxPHFitter()

df['event'] = df['lost'].isin([1,2,3])

cph.fit(
    df[variables + ['years', 'event', 'region']],
    duration_col='years',
    event_col='event',
    strata=['region']
)

cph.print_summary(decimals=3)

<lifelines.CoxPHFitter: fitted with 438 total observations, 111 right-censored observations>
             duration col = 'years'
                event col = 'event'
                   strata = region
      baseline estimation = breslow
   number of observations = 438
number of events observed = 327
   partial log-likelihood = -1280.538
         time fit was run = 2026-04-24 04:34:41 UTC

---
            coef exp(coef)  se(coef)  coef lower 95%  coef upper 95% exp(coef) lower 95% exp(coef) upper 95%
covariate
manner     0.383     1.466     0.155           0.079           0.687               1.082               1.988
start     -0.018     0.983     0.008          -0.033          -0.002               0.967               0.998
military  -0.231     0.794     0.163          -0.552           0.089               0.576               1.093
age        0.023     1.023     0.006           0.012           0.034               1.012               1.034
conflict   0.127     1.136     0.131          -0.130           0.384               0.878               1.469
loginc    -0.182     0.833     0.083          -0.344          -0.020               0.709               0.980
growth    -0.002     0.998     0.021          -0.044           0.040               0.957               1.041
pop       -0.000     1.000     0.001          -0.001           0.001               0.999               1.001
land       0.000     1.000     0.000          -0.000           0.000               1.000               1.000
literacy   0.001     1.001     0.003          -0.006           0.007               0.994               1.007

           cmp to      z       p  -log2(p)
covariate
manner      0.000  2.466   0.014     6.196
start       0.000 -2.152   0.031     4.994
military    0.000 -1.415   0.157     2.670
age         0.000  4.091 <0.0005    14.504
conflict    0.000  0.968   0.333     1.586
loginc      0.000 -2.206   0.027     5.190
growth      0.000 -0.095   0.924     0.114
pop         0.000 -0.099   0.921     0.119
land        0.000  0.228   0.820     0.287
literacy    0.000  0.219   0.827     0.274
---
Concordance = 0.602
Partial AIC = 2581.077
log-likelihood ratio test = 35.243 on 10 df
-log2(p) of ll-ratio test = 13.105

In [5]:
df['event'] = df['lost'].isin([3])

cph.fit(
    df[variables + ['years', 'event', 'region']],
    duration_col='years',
    event_col='event',
    strata=['region']
)

cph.print_summary(decimals=3)

<lifelines.CoxPHFitter: fitted with 438 total observations, 284 right-censored observations>
             duration col = 'years'
                event col = 'event'
                   strata = region
      baseline estimation = breslow
   number of observations = 438
number of events observed = 154
   partial log-likelihood = -601.020
         time fit was run = 2026-04-24 04:34:42 UTC

---
            coef exp(coef)  se(coef)  coef lower 95%  coef upper 95% exp(coef) lower 95% exp(coef) upper 95%
covariate
manner     0.928     2.530     0.220           0.496           1.360               1.642               3.897
start     -0.033     0.967     0.012          -0.057          -0.010               0.944               0.990
military  -0.414     0.661     0.228          -0.860           0.032               0.423               1.033
age        0.009     1.009     0.008          -0.008           0.026               0.992               1.026
conflict   0.504     1.656     0.203           0.106           0.903               1.112               2.467
loginc    -0.433     0.648     0.141          -0.710          -0.156               0.491               0.855
growth    -0.049     0.953     0.031          -0.110           0.012               0.896               1.012
pop       -0.001     0.999     0.002          -0.004           0.002               0.996               1.002
land       0.000     1.000     0.000          -0.000           0.000               1.000               1.000
literacy  -0.006     0.994     0.005          -0.015           0.003               0.986               1.003

           cmp to      z       p  -log2(p)
covariate
manner      0.000  4.210 <0.0005    15.256
start       0.000 -2.745   0.006     7.367
military    0.000 -1.818   0.069     3.857
age         0.000  1.062   0.288     1.796
conflict    0.000  2.481   0.013     6.253
loginc      0.000 -3.066   0.002     8.849
growth      0.000 -1.561   0.118     3.078
pop         0.000 -0.665   0.506     0.983
land        0.000  0.251   0.802     0.318
literacy    0.000 -1.259   0.208     2.264
---
Concordance = 0.694
Partial AIC = 1222.040
log-likelihood ratio test = 71.404 on 10 df
-log2(p) of ll-ratio test = 35.294

In [6]:
df['event'] = df['lost'].isin([2])

cph.fit(
    df[variables + ['years', 'event', 'region']],
    duration_col='years',
    event_col='event',
    strata=['region']
)

cph.print_summary(decimals=3)

<lifelines.CoxPHFitter: fitted with 438 total observations, 411 right-censored observations>
             duration col = 'years'
                event col = 'event'
                   strata = region
      baseline estimation = breslow
   number of observations = 438
number of events observed = 27
   partial log-likelihood = -77.688
         time fit was run = 2026-04-24 04:34:42 UTC

---
            coef exp(coef)  se(coef)  coef lower 95%  coef upper 95% exp(coef) lower 95% exp(coef) upper 95%
covariate
manner     0.303     1.353     0.702          -1.073           1.679               0.342               5.358
start     -0.059     0.943     0.035          -0.128           0.011               0.880               1.011
military  -0.299     0.742     0.783          -1.833           1.235               0.160               3.437
age        0.079     1.083     0.020           0.039           0.119               1.040               1.127
conflict  -0.554     0.575     0.509          -1.550           0.443               0.212               1.557
loginc     0.195     1.215     0.283          -0.360           0.750               0.698               2.116
growth     0.092     1.097     0.085          -0.075           0.260               0.928               1.296
pop        0.001     1.001     0.002          -0.003           0.005               0.997               1.005
land       0.000     1.000     0.000          -0.000           0.000               1.000               1.000
literacy  -0.012     0.988     0.014          -0.039           0.014               0.962               1.014

           cmp to      z       p  -log2(p)
covariate
manner      0.000  0.431   0.666     0.586
start       0.000 -1.658   0.097     3.360
military    0.000 -0.382   0.702     0.510
age         0.000  3.896 <0.0005    13.318
conflict    0.000 -1.089   0.276     1.856
loginc      0.000  0.688   0.491     1.026
growth      0.000  1.081   0.280     1.838
pop         0.000  0.434   0.664     0.590
land        0.000  0.193   0.847     0.239
literacy    0.000 -0.911   0.363     1.464
---
Concordance = 0.788
Partial AIC = 175.376
log-likelihood ratio test = 25.107 on 10 df
-log2(p) of ll-ratio test = 7.602

In [7]:
df['event'] = df['lost'].isin([1])

cph.fit(
    df[variables + ['years', 'event', 'region']],
    duration_col='years',
    event_col='event',
    strata=['region']
)

cph.print_summary(decimals=3)

<lifelines.CoxPHFitter: fitted with 438 total observations, 292 right-censored observations>
             duration col = 'years'
                event col = 'event'
                   strata = region
      baseline estimation = breslow
   number of observations = 438
number of events observed = 146
   partial log-likelihood = -569.703
         time fit was run = 2026-04-24 04:34:42 UTC

---
            coef exp(coef)  se(coef)  coef lower 95%  coef upper 95% exp(coef) lower 95% exp(coef) upper 95%
covariate
manner    -0.308     0.735     0.257          -0.813           0.196               0.444               1.217
start      0.002     1.002     0.012          -0.021           0.026               0.979               1.026
military  -0.012     0.988     0.261          -0.523           0.499               0.593               1.646
age        0.024     1.024     0.009           0.007           0.041               1.007               1.042
conflict  -0.030     0.971     0.204          -0.429           0.369               0.651               1.447
loginc    -0.131     0.878     0.119          -0.365           0.103               0.694               1.109
growth     0.034     1.034     0.035          -0.034           0.102               0.967               1.107
pop        0.000     1.000     0.001          -0.001           0.002               0.999               1.002
land      -0.000     1.000     0.000          -0.000           0.000               1.000               1.000
literacy   0.014     1.014     0.006           0.003           0.025               1.003               1.025

           cmp to      z     p  -log2(p)
covariate
manner      0.000 -1.197 0.231     2.113
start       0.000  0.199 0.842     0.248
military    0.000 -0.046 0.963     0.054
age         0.000  2.780 0.005     7.525
conflict    0.000 -0.147 0.883     0.179
loginc      0.000 -1.095 0.274     1.869
growth      0.000  0.982 0.326     1.616
pop         0.000  0.486 0.627     0.674
land        0.000 -0.371 0.710     0.493
literacy    0.000  2.439 0.015     6.086
---
Concordance = 0.587
Partial AIC = 1159.407
log-likelihood ratio test = 29.049 on 10 df
-log2(p) of ll-ratio test = 9.675